name: link_checker

on:
  push:
    branches:
    - main
    - staging
  pull_request:

jobs:
  link_checker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler-cache: true

    - name: Build site
      env:
        JEKYLL_ENV: production
      run: make _site

    - name: Link Checker
      uses: lycheeverse/lychee-action@v1.2.0
      with:
        args: --no-progress --exclude assets --exclude "file:" --exclude "javascript:" -- _site/**/*.html
        fail: true
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
